# Generated by Django 3.0.7 on 2020-07-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobsearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company_requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perks', models.CharField(max_length=200)),
                ('Skill_requirement', models.CharField(max_length=200)),
                ('jobsearch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.jobsearch')),
            ],
        ),
    ]
